"""add price, address and epc columns

Revision ID: 187b38f6e497
Revises: a1442d6e9486
Create Date: 2026-07-21 14:25:26.683952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '187b38f6e497'
down_revision: Union[str, None] = 'a1442d6e9486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('epc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.drop_column('epc')
        batch_op.drop_column('address')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
