"""add status column

Revision ID: 5a718d010e52
Revises: 8fce92544698
Create Date: 2026-07-21 16:32:34.489055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a718d010e52'
down_revision: Union[str, None] = '8fce92544698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='available'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
