"""

Revision ID: 6d206eddcb0c
Revises: 
Create Date: 2026-07-21 21:23:45.153680

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d206eddcb0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basehouse',
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_price', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bedrooms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('living_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('surface_ground', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('epc', sa.Integer(), nullable=True),
    sa.Column('epc_is_estimated', sa.Boolean(), nullable=True),
    sa.Column('garage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('garden', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('source', 'link')
    )
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_basehouse_link'), ['link'], unique=False)
        batch_op.create_index(batch_op.f('ix_basehouse_source'), ['source'], unique=False)

    op.create_table('propertysalesrecordorm',
    sa.Column('nis_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('all_houses_transactions', sa.Integer(), nullable=True),
    sa.Column('all_houses_median', sa.Float(), nullable=True),
    sa.Column('all_houses_q1', sa.Float(), nullable=True),
    sa.Column('all_houses_q3', sa.Float(), nullable=True),
    sa.Column('terraced_semi_transactions', sa.Integer(), nullable=True),
    sa.Column('terraced_semi_median', sa.Float(), nullable=True),
    sa.Column('terraced_semi_q1', sa.Float(), nullable=True),
    sa.Column('terraced_semi_q3', sa.Float(), nullable=True),
    sa.Column('detached_transactions', sa.Integer(), nullable=True),
    sa.Column('detached_median', sa.Float(), nullable=True),
    sa.Column('detached_q1', sa.Float(), nullable=True),
    sa.Column('detached_q3', sa.Float(), nullable=True),
    sa.Column('apartments_transactions', sa.Integer(), nullable=True),
    sa.Column('apartments_median', sa.Float(), nullable=True),
    sa.Column('apartments_q1', sa.Float(), nullable=True),
    sa.Column('apartments_q3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nis_code', 'locality', 'year', 'period')
    )
    with op.batch_alter_table('propertysalesrecordorm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_locality'), ['locality'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_nis_code'), ['nis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertysalesrecordorm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_year'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_period'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_nis_code'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_locality'))

    op.drop_table('propertysalesrecordorm')
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_basehouse_source'))
        batch_op.drop_index(batch_op.f('ix_basehouse_link'))

    op.drop_table('basehouse')
    # ### end Alembic commands ###
