"""add garage and garden columns

Revision ID: 8fce92544698
Revises: 187b38f6e497
Create Date: 2026-07-21 15:40:22.186472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fce92544698'
down_revision: Union[str, None] = '187b38f6e497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('garden', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basehouse', schema=None) as batch_op:
        batch_op.drop_column('garden')
        batch_op.drop_column('garage')

    # ### end Alembic commands ###
