"""

Revision ID: a1442d6e9486
Revises:
Create Date: 2025-11-29 18:22:07.223528

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1442d6e9486"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basehouse",
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_price", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bedrooms", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("living_area", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("surface_ground", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("source", "created_at", "link"),
    )
    with op.batch_alter_table("basehouse", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_basehouse_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_basehouse_link"), ["link"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_basehouse_source"), ["source"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("basehouse", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_basehouse_source"))
        batch_op.drop_index(batch_op.f("ix_basehouse_link"))
        batch_op.drop_index(batch_op.f("ix_basehouse_created_at"))

    op.drop_table("basehouse")
    # ### end Alembic commands ###
