"""

Revision ID: c6795426538c
Revises: 5a718d010e52
Create Date: 2026-07-21 18:40:43.134186

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6795426538c'
down_revision: Union[str, None] = '5a718d010e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertysalesrecordorm',
    sa.Column('nis_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('all_houses_transactions', sa.Integer(), nullable=True),
    sa.Column('all_houses_median', sa.Float(), nullable=True),
    sa.Column('all_houses_q1', sa.Float(), nullable=True),
    sa.Column('all_houses_q3', sa.Float(), nullable=True),
    sa.Column('terraced_semi_transactions', sa.Integer(), nullable=True),
    sa.Column('terraced_semi_median', sa.Float(), nullable=True),
    sa.Column('terraced_semi_q1', sa.Float(), nullable=True),
    sa.Column('terraced_semi_q3', sa.Float(), nullable=True),
    sa.Column('detached_transactions', sa.Integer(), nullable=True),
    sa.Column('detached_median', sa.Float(), nullable=True),
    sa.Column('detached_q1', sa.Float(), nullable=True),
    sa.Column('detached_q3', sa.Float(), nullable=True),
    sa.Column('apartments_transactions', sa.Integer(), nullable=True),
    sa.Column('apartments_median', sa.Float(), nullable=True),
    sa.Column('apartments_q1', sa.Float(), nullable=True),
    sa.Column('apartments_q3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nis_code', 'locality', 'year', 'period')
    )
    with op.batch_alter_table('propertysalesrecordorm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_locality'), ['locality'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_nis_code'), ['nis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_propertysalesrecordorm_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertysalesrecordorm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_year'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_period'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_nis_code'))
        batch_op.drop_index(batch_op.f('ix_propertysalesrecordorm_locality'))

    op.drop_table('propertysalesrecordorm')
    # ### end Alembic commands ###
